update GitHub Actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: CI/CD Advanced Julia
+name: Room-Occupancy-Deployment
 
 on:
   push:
@@ -23,32 +23,33 @@ jobs:
 
       - name: Install dependencies
         run: |
-          pip install pandas scikit-learn mlflow dagshub matplotlib seaborn
+          pip install -r Membangun_model/requirements.txt
 
       - name: Run training script
         env:
           MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
           MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
         run: |
-          rm -rf mlruns
-          python MLProject/modelling_tuning.py
+          python Membangun_model/modelling_tuning.py
 
-      - name: Get latest MLflow run_id
+      - name: Commit and Push processed data
         run: |
-          ID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
-          echo "RUN_ID=$ID" >> $GITHUB_ENV
-          echo "Ditemukan ID: $ID"
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add Membangun_model/namadataset_preprocessing/occupancy_processed.csv
+          git commit -m "Update processed dataset from GitHub Actions" || echo "No changes to commit"
+          git push
 
-      - name: Install Python dependencies
-        run: pip install -r MLProject/requirements.txt
-
-      - name: Build Docker Model
-        run: |
-          python MLProject/modelling_tuning.py
-
+      - name: Build Docker Image
+        run: | 
           MODEL_DIR=$(find mlruns -name "MLmodel" -exec dirname {} \; | head -n 1)
           echo "Robot menemukan model di: $MODEL_DIR"
-
+          
+          if [ -z "$MODEL_DIR" ]; then
+            echo "Error: Folder model tidak ditemukan!"
+            exit 1
+          fi
+          
           mlflow models build-docker -m "$MODEL_DIR" -n "occupancy-classifier-prod" --install-mlflow
 
       - name: Log in to Docker Hub
